### ISSUE TITLE
Replace SARIF processing with Grype output

### ISSUE THREAD

**Issue by kzantow** [anchore/scan-action#146]
We have implemented SARIF output in Grype and need to remove it from this action and replace with what is implemented in Grype.

Once https://github.com/anchore/grype/pull/654 is merged and we replace the SARIF output here, it will resolve:
#60, #61, #98, and #116 as well as ensuring that future changes to the Grype data model don't prevent SARIF from being generated properly (as is the case now).

**Comment by dmkim22-lguplus** [comment]
Hello, 

With v3.2.1, I'm receiving below error when pushing SARIF report with codeql-action/upload-sarif.
This happens when my FROM image is an openjdk "slim". Everything is fine if I use an alpine image, or specify anchore/scan-action@v3.2.0.


```
Uploading results
  Processing sarif files: ["./results.sarif"]
  Error: Unexpected end of JSON input
  SyntaxError: Unexpected end of JSON input
      at JSON.parse (<anonymous>)
      at validateSarifFileSchema (/home/runner/work/_actions/github/codeql-action/v1/lib/upload-lib.js:188:24)
      at uploadFiles (/home/runner/work/_actions/github/codeql-action/v1/lib/upload-lib.js:265:9)
      at Object.uploadFromActions (/home/runner/work/_actions/github/codeql-action/v1/lib/upload-lib.js:[13](https://github.com/lguplus-ccoe/container-hardening/runs/5731083442?check_suite_focus=true#step:5:13)7:[18](https://github.com/lguplus-ccoe/container-hardening/runs/5731083442?check_suite_focus=true#step:5:18))
      at async run (/home/runner/work/_actions/github/codeql-action/v1/lib/upload-sarif-action.js:51:30)
      at async runWrapper (/home/runner/work/_actions/github/codeql-action/v1/lib/upload-sarif-action.js:69:9)

```
