### ISSUE TITLE
Errors running the download action

### ISSUE THREAD

**Issue by nkreiger** [anchore/scan-action#211]
/usr/bin/chmod +x /home/runner/work/_temp/d02a7871-c656-4d90-b4cf-3c07111c18cb
/home/runner/work/_temp/d02a7871-c656-4d90-b4cf-3c07111c18cb -b /home/runner/work/_temp/d02a7871-c656-4d90-b4cf-3c07111c18cb_grype v0.56.0
[info] checking github for release tag='v0.56.0' 
Error:  unable to find tag='' 
Error:  do not specify a version or select a valid version from https://github.com/anchore/grype/releases 
node:fs:1551
  handleErrorFromBinding(ctx);
  ^

Error: ENOENT: no such file or directory, stat '/home/runner/work/_temp/d02a7871-c656-4d90-b4cf-3c07111c18cb_grype/grype'
    at Object.statSync (node:fs:1551:3)
    at Object.<anonymous> (/home/runner/work/_actions/anchore/scan-action/v3/dist/index.js:4642:17)
    at Generator.next (<anonymous>)
    at /home/runner/work/_actions/anchore/scan-action/v3/dist/index.js:4231:71
    at new Promise (<anonymous>)
    at __webpack_modules__.7784.__awaiter (/home/runner/work/_actions/anchore/scan-action/v3/dist/index.js:4227:12)
    at Object.cacheFile (/home/runner/work/_actions/anchore/scan-action/v3/dist/index.js:4637:12)
    at downloadGrype (/home/runner/work/_actions/anchore/scan-action/v3/dist/index.js:41:16)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async installGrype (/home/runner/work/_actions/anchore/scan-action/v3/dist/index.js:48:17) ***
  errno: -2,
  syscall: 'stat',
  code: 'ENOENT',
  path: '/home/runner/work/_temp/d02a7871-c656-4d90-b4cf-3c07111c18cb_grype/grype'

**Comment by nkreiger** [comment]
This was working fine for months, did something change?

**Comment by nkreiger** [comment]
https://github.com/anchore/grype/issues/1102

**Comment by kzantow** [comment]
Hi @nkreiger I've just tried the standard Grype download script out for macOS and Linux and it seems to be working fine for me at this point, could you retry?

NOTE I also saw a failure yesterday where https://github.com/anchore/grype/releases/download/v0.56.0/grype_0.56.0_linux_arm64.deb was returning 403 for some reason, but seems to be fine now.

**Comment by nkreiger** [comment]
Can confirm it is working now @kzantow
